- name: Install Node.js on EC2 instance
  hosts: ec2_instance
  gather_facts: yes
  vars:
    ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ec2-user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        state: present

    - name: Install Node.js
      yum:
        name: nodejs
        state: present
