- name: Install Node.js on EC2 instance
  hosts: ec2_instance
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ec2-user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Get NodeSource Node.js Binary Distributions setup script
      get_url:
        url: https://rpm.nodesource.com/setup_14.x
        dest: /tmp/setup_14.x
        mode: '0755'

    - name: Run setup script
      command: /tmp/setup_14.x

    - name: Install Node.js
      yum:
        name: nodejs
        state: present
