- name: Install Node.js on EC2 instance
  hosts: ec2_instance
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ec2-user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
        
    - name: Enable Node.js from Amazon Linux Extras
      command: amazon-linux-extras install -y nodejs

    - name: Verify Node.js installation
      command: node -v
      register: node_version
      changed_when: false

    - name: Print Node.js version
      debug:
        msg: "Node.js version is {{ node_version.stdout }}"
