---
- name: Install Node.js on EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Ensure system is updated
      yum: 
        upgrade: yes
        update_cache: yes

    - name: Install Node.js
      yum:
        name: nodejs
        state: present
        update_cache: yes
