name: Provision EC2 and Run Ansible

on:
  push:
    branches:
      - master

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List out directory
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init
        working-directory: terraform-ec2-ssh

      - name: Terraform apply
        id: terraform
        run: terraform apply -auto-approve
        working-directory: terraform-ec2-ssh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get EC2 instance IP address
        id: ec2
        run: echo "::set-output name=ip_address::$(aws ec2 describe-instances --filters 'Name=tag:Name,Values=cloudysky-terraform-ec2-ansible' --query 'Reservations[].Instances[].PublicIpAddress' --output text)"

      - name: Wait for EC2 instance to be available
        id: wait
        run: |
          ip_address="${{ steps.ec2.outputs.ip_address }}"
          aws ec2 wait instance-status-ok --instance-ids $(aws ec2 describe-instances --filters "Name=private-ip-address,Values=$ip_address" --query 'Reservations[].Instances[].InstanceId' --output text)

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: sudo yum update && sudo yum install -y ansible

      - name: Run Ansible playbook
        run: ansible-playbook -e "target_ip=${{ steps.ec2.outputs.ip_address }}" playbook.yml
