name: Provision EC2 and Run Ansible

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List out directory
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        id: terraform
        run: terraform apply -auto-approve

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Print Instance Public IP
        id: instance
        run: |
          terraform version
          terraform output -raw instance_public_ip
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


      - name: Output Instance Public IP
        id: ip
        run: |
          echo "::set-output name=ip::$(terraform output -raw instance_public_ip)"
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
     
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: print ip
        run: echo ${{ needs.terraform.outputs.ip }}

      - name: Wait for SSH
        run: |
          while ((1)); do
            nc -zvw3 ${{ needs.terraform.outputs.ip }} 22 && echo "SSH is ready" && break
            echo "Waiting for SSH..."
            sleep 5
          done

      - name: Run Ansible playbook
        run: |
          echo "[ec2]" > inventory
          echo "${{ needs.terraform.outputs.ip }}" >> inventory
          ansible-playbook -i inventory playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
