name: Provision EC2 and Run Ansible

on:
  push:
    branches:
      - master

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List out directory
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init
        working-directory: terraform-ec2-ssh

      - name: Terraform apply
        id: terraform
        run: terraform apply -auto-approve
        working-directory: terraform-ec2-ssh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Output Instance Public IP
        id: instance
        run: |
          echo "::set-output name=ip::$(terraform output -raw instance_public_ip)"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: Wait for SSH
        run: |
          until nc -zvw3 ${{ needs.setup.outputs.ip }} 22; do
            sleep 5
          done

      - name: Run Ansible playbook
        run: ansible-playbook -i "${{ needs.setup.outputs.ip }}," playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}