name: Delete Terraform Workspace
on:
  push:
    branches:
      - workspace

env:
  TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }} # Your Terraform Cloud API token
  TF_WORKSPACE: terraform-sandeep-aws

jobs:
  runterraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List out directory
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init 

      - name: Terraform list workspaces
        run: terraform workspace select $TF_WORKSPACE

      - name: Terraform delete workspace
        run: terraform workspace delete $TF_WORKSPACE -force



